/**
 * EmployeeEFCrud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Employee from './model/Employee';
import Roles from './model/Roles';
import User from './model/User';
import UserRoles from './model/UserRoles';
import Userdto from './model/Userdto';
import AuthApi from './api/AuthApi';
import EmployeesApi from './api/EmployeesApi';
import FeaturesApi from './api/FeaturesApi';
import RolesApi from './api/RolesApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EmployeeEfCrud = require('index'); // See note below*.
* var xxxSvc = new EmployeeEfCrud.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EmployeeEfCrud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EmployeeEfCrud.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EmployeeEfCrud.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Employee model constructor.
     * @property {module:model/Employee}
     */
    Employee,

    /**
     * The Roles model constructor.
     * @property {module:model/Roles}
     */
    Roles,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserRoles model constructor.
     * @property {module:model/UserRoles}
     */
    UserRoles,

    /**
     * The Userdto model constructor.
     * @property {module:model/Userdto}
     */
    Userdto,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The EmployeesApi service constructor.
    * @property {module:api/EmployeesApi}
    */
    EmployeesApi,

    /**
    * The FeaturesApi service constructor.
    * @property {module:api/FeaturesApi}
    */
    FeaturesApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi
};
