/**
 * EmployeeEFCrud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmployeeEfCrud);
  }
}(this, function(expect, EmployeeEfCrud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EmployeeEfCrud.EmployeesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmployeesApi', function() {
    describe('apiEmployeesGet', function() {
      it('should call apiEmployeesGet successfully', function(done) {
        //uncomment below and update the code to test apiEmployeesGet
        //instance.apiEmployeesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEmployeesIdDelete', function() {
      it('should call apiEmployeesIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiEmployeesIdDelete
        //instance.apiEmployeesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEmployeesIdGet', function() {
      it('should call apiEmployeesIdGet successfully', function(done) {
        //uncomment below and update the code to test apiEmployeesIdGet
        //instance.apiEmployeesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEmployeesIdPut', function() {
      it('should call apiEmployeesIdPut successfully', function(done) {
        //uncomment below and update the code to test apiEmployeesIdPut
        //instance.apiEmployeesIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiEmployeesPost', function() {
      it('should call apiEmployeesPost successfully', function(done) {
        //uncomment below and update the code to test apiEmployeesPost
        //instance.apiEmployeesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
