/**
 * EmployeeEFCrud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmployeeEfCrud);
  }
}(this, function(expect, EmployeeEfCrud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EmployeeEfCrud.RolesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RolesApi', function() {
    describe('apiRolesAddEmployeeRolePost', function() {
      it('should call apiRolesAddEmployeeRolePost successfully', function(done) {
        //uncomment below and update the code to test apiRolesAddEmployeeRolePost
        //instance.apiRolesAddEmployeeRolePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiRolesAddRolesPost', function() {
      it('should call apiRolesAddRolesPost successfully', function(done) {
        //uncomment below and update the code to test apiRolesAddRolesPost
        //instance.apiRolesAddRolesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiRolesDeleteEmpRoleDelete', function() {
      it('should call apiRolesDeleteEmpRoleDelete successfully', function(done) {
        //uncomment below and update the code to test apiRolesDeleteEmpRoleDelete
        //instance.apiRolesDeleteEmpRoleDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiRolesShowEmployeeRolesGet', function() {
      it('should call apiRolesShowEmployeeRolesGet successfully', function(done) {
        //uncomment below and update the code to test apiRolesShowEmployeeRolesGet
        //instance.apiRolesShowEmployeeRolesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiRolesShowRolesGet', function() {
      it('should call apiRolesShowRolesGet successfully', function(done) {
        //uncomment below and update the code to test apiRolesShowRolesGet
        //instance.apiRolesShowRolesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
