name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies and generate/update package-lock.json
      run: |
        npm install
        git add package-lock.json
        git commit -m "Update package-lock.json" || true
        git push origin main

    - name: Build SDK (replace with your build command if needed)
      run: npm run build

    - name: Publish to npm
      run: npm publish

      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
