name: Publish package to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the new version for the package'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Configure Git, Commit, Pull, and Push changes
      run: |
        git config --global user.email "dprakash2101@gmail.com"
        git config --global user.name "dprakash2101"
        git pull origin main
        git commit -am "Bump version to ${{ github.event.inputs.version }}" --allow-empty
        git push origin main

    - name: Build SDK
      run: npm run build

    - name: Authenticate with npm
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.AUTOMATE_NJS_TOKEN }}" > ~/.npmrc

    - name: Publish to npm (dry run)
      run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.AUTOMATE_NJS_TOKEN }}
