name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the Actions tab in your repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NPM_CONFIG_SCOPE: "@dprakash2101"
          NPM_CONFIG_PREPUBLISH: "false"
